### YamlMime:JavaType
uid: "com.azure.resourcemanager.appcontainers.models.DefaultErrorResponseErrorException"
fullName: "com.azure.resourcemanager.appcontainers.models.DefaultErrorResponseErrorException"
name: "DefaultErrorResponseErrorException"
nameWithType: "DefaultErrorResponseErrorException"
summary: "Exception thrown for an invalid response with DefaultErrorResponseError information."
inheritances:
- "<xref href=\"java.lang.Object?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.Throwable?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.Exception?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.RuntimeException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"com.azure.core.exception.AzureException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"com.azure.core.exception.HttpResponseException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"com.azure.core.management.exception.ManagementException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
inheritedMembers:
- "com.azure.core.exception.HttpResponseException.getResponse()"
- "com.azure.core.management.exception.ManagementException.getValue()"
- "com.azure.core.management.exception.ManagementException.toString()"
- "java.lang.Object.clone()"
- "java.lang.Object.equals(java.lang.Object)"
- "java.lang.Object.finalize()"
- "java.lang.Object.getClass()"
- "java.lang.Object.hashCode()"
- "java.lang.Object.notify()"
- "java.lang.Object.notifyAll()"
- "java.lang.Object.wait()"
- "java.lang.Object.wait(long)"
- "java.lang.Object.wait(long,int)"
- "java.lang.Throwable.addSuppressed(java.lang.Throwable)"
- "java.lang.Throwable.fillInStackTrace()"
- "java.lang.Throwable.getCause()"
- "java.lang.Throwable.getLocalizedMessage()"
- "java.lang.Throwable.getMessage()"
- "java.lang.Throwable.getStackTrace()"
- "java.lang.Throwable.getSuppressed()"
- "java.lang.Throwable.initCause(java.lang.Throwable)"
- "java.lang.Throwable.printStackTrace()"
- "java.lang.Throwable.printStackTrace(java.io.PrintStream)"
- "java.lang.Throwable.printStackTrace(java.io.PrintWriter)"
- "java.lang.Throwable.setStackTrace(java.lang.StackTraceElement[])"
syntax: "public final class DefaultErrorResponseErrorException extends ManagementException"
constructors:
- "com.azure.resourcemanager.appcontainers.models.DefaultErrorResponseErrorException.DefaultErrorResponseErrorException(java.lang.String,com.azure.core.http.HttpResponse)"
- "com.azure.resourcemanager.appcontainers.models.DefaultErrorResponseErrorException.DefaultErrorResponseErrorException(java.lang.String,com.azure.core.http.HttpResponse,com.azure.resourcemanager.appcontainers.models.DefaultErrorResponseError)"
methods:
- "com.azure.resourcemanager.appcontainers.models.DefaultErrorResponseErrorException.getValue()"
type: "class"
desc: "Exception thrown for an invalid response with DefaultErrorResponseError information."
metadata: {}
package: "com.azure.resourcemanager.appcontainers.models"
artifact: com.azure.resourcemanager:azure-resourcemanager-appcontainers:1.0.0-beta.3
