### YamlMime:JavaMember
uid: "com.azure.resourcemanager.synapse.models.DataConnectionValidationResult.withErrorMessage*"
fullName: "com.azure.resourcemanager.synapse.models.DataConnectionValidationResult.withErrorMessage"
name: "withErrorMessage"
nameWithType: "DataConnectionValidationResult.withErrorMessage"
members:
- uid: "com.azure.resourcemanager.synapse.models.DataConnectionValidationResult.withErrorMessage(java.lang.String)"
  fullName: "com.azure.resourcemanager.synapse.models.DataConnectionValidationResult.withErrorMessage(String errorMessage)"
  name: "withErrorMessage(String errorMessage)"
  nameWithType: "DataConnectionValidationResult.withErrorMessage(String errorMessage)"
  summary: "Set the errorMessage property: A message which indicates a problem in data connection validation."
  parameters:
  - description: "the errorMessage value to set."
    name: "errorMessage"
    type: "<xref href=\"java.lang.String?alt=java.lang.String&text=String\" data-throw-if-not-resolved=\"False\" />"
  syntax: "public DataConnectionValidationResult withErrorMessage(String errorMessage)"
  returns:
    description: "the DataConnectionValidationResult object itself."
    type: "<xref href=\"com.azure.resourcemanager.synapse.models.DataConnectionValidationResult?alt=com.azure.resourcemanager.synapse.models.DataConnectionValidationResult&text=DataConnectionValidationResult\" data-throw-if-not-resolved=\"False\" />"
type: "method"
metadata: {}
package: "com.azure.resourcemanager.synapse.models"
artifact: com.azure.resourcemanager:azure-resourcemanager-synapse:1.0.0-beta.4
