### YamlMime:JavaType
uid: "com.azure.security.keyvault.certificates.models.CertificateOperationError"
fullName: "com.azure.security.keyvault.certificates.models.CertificateOperationError"
name: "CertificateOperationError"
nameWithType: "CertificateOperationError"
summary: "Represents the error in <xref uid=\"com.azure.security.keyvault.certificates.models.CertificateOperation\" data-throw-if-not-resolved=\"false\" data-raw-source=\"CertificateOperation\"></xref>."
inheritances:
- "<xref href=\"java.lang.Object?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
inheritedMembers:
- "java.lang.Object.clone()"
- "java.lang.Object.equals(java.lang.Object)"
- "java.lang.Object.finalize()"
- "java.lang.Object.getClass()"
- "java.lang.Object.hashCode()"
- "java.lang.Object.notify()"
- "java.lang.Object.notifyAll()"
- "java.lang.Object.toString()"
- "java.lang.Object.wait()"
- "java.lang.Object.wait(long)"
- "java.lang.Object.wait(long,int)"
syntax: "public final class CertificateOperationError"
constructors:
- uid: "com.azure.security.keyvault.certificates.models.CertificateOperationError.CertificateOperationError()"
  fullName: "com.azure.security.keyvault.certificates.models.CertificateOperationError.CertificateOperationError()"
  name: "CertificateOperationError()"
  nameWithType: "CertificateOperationError.CertificateOperationError()"
  syntax: "public CertificateOperationError()"
methods:
- uid: "com.azure.security.keyvault.certificates.models.CertificateOperationError.getCode()"
  fullName: "com.azure.security.keyvault.certificates.models.CertificateOperationError.getCode()"
  name: "getCode()"
  nameWithType: "CertificateOperationError.getCode()"
  summary: "Get the code."
  syntax: "public String getCode()"
  desc: "Get the code."
  returns:
    description: "the code"
    type: "<xref href=\"java.lang.String?alt=java.lang.String&text=String\" data-throw-if-not-resolved=\"False\" />"
- uid: "com.azure.security.keyvault.certificates.models.CertificateOperationError.getInnerError()"
  fullName: "com.azure.security.keyvault.certificates.models.CertificateOperationError.getInnerError()"
  name: "getInnerError()"
  nameWithType: "CertificateOperationError.getInnerError()"
  summary: "Get the inner error."
  syntax: "public CertificateOperationError getInnerError()"
  desc: "Get the inner error."
  returns:
    description: "the inner error"
    type: "<xref href=\"com.azure.security.keyvault.certificates.models.CertificateOperationError?alt=com.azure.security.keyvault.certificates.models.CertificateOperationError&text=CertificateOperationError\" data-throw-if-not-resolved=\"False\" />"
- uid: "com.azure.security.keyvault.certificates.models.CertificateOperationError.getMessage()"
  fullName: "com.azure.security.keyvault.certificates.models.CertificateOperationError.getMessage()"
  name: "getMessage()"
  nameWithType: "CertificateOperationError.getMessage()"
  summary: "Get the message."
  syntax: "public String getMessage()"
  desc: "Get the message."
  returns:
    description: "the message"
    type: "<xref href=\"java.lang.String?alt=java.lang.String&text=String\" data-throw-if-not-resolved=\"False\" />"
type: "class"
desc: "Represents the error in <xref uid=\"com.azure.security.keyvault.certificates.models.CertificateOperation\" data-throw-if-not-resolved=\"false\" data-raw-source=\"CertificateOperation\"></xref>."
metadata: {}
package: "com.azure.security.keyvault.certificates.models"
artifact: com.azure:azure-security-keyvault-certificates:4.3.0-beta.5
