### YamlMime:JavaMember
nameWithType: ReminderNotFoundException.ReminderNotFoundException
type: constructor
members:
- fullName: microsoft.servicefabric.actors.ReminderNotFoundException.ReminderNotFoundException()
  name: ReminderNotFoundException()
  nameWithType: ReminderNotFoundException.ReminderNotFoundException()
  summary: <p>Initializes a new instance of the <xref uid="microsoft.servicefabric.actors.ReminderNotFoundException" data-throw-if-not-resolved="false">ReminderNotFoundException</xref> class. </p>
  syntax: public ReminderNotFoundException()
  uid: microsoft.servicefabric.actors.ReminderNotFoundException.ReminderNotFoundException()
- fullName: microsoft.servicefabric.actors.ReminderNotFoundException.ReminderNotFoundException(String message)
  name: ReminderNotFoundException(String message)
  nameWithType: ReminderNotFoundException.ReminderNotFoundException(String message)
  parameters:
  - description: <p>input message </p>
    name: message
    type: <xref href="String?alt=String&text=String" data-throw-if-not-resolved="False"/>
  summary: >-
    <p>Initializes a new instance of the <xref uid="microsoft.servicefabric.actors.ReminderNotFoundException" data-throw-if-not-resolved="false">ReminderNotFoundException</xref> class with a specified error message.</p>

    <p></p>
  syntax: public ReminderNotFoundException(String message)
  uid: microsoft.servicefabric.actors.ReminderNotFoundException.ReminderNotFoundException(String)
- fullName: microsoft.servicefabric.actors.ReminderNotFoundException.ReminderNotFoundException(String message, Throwable cause)
  name: ReminderNotFoundException(String message, Throwable cause)
  nameWithType: ReminderNotFoundException.ReminderNotFoundException(String message, Throwable cause)
  parameters:
  - description: <p>The error message that explains the reason for the exception. </p>
    name: message
    type: <xref href="String?alt=String&text=String" data-throw-if-not-resolved="False"/>
  - description: <p>The exception that is the cause of the current exception, or a null reference if no inner exception is specified. </p>
    name: cause
    type: <xref href="Throwable?alt=Throwable&text=Throwable" data-throw-if-not-resolved="False"/>
  summary: >-
    <p>Initializes a new instance of the <xref uid="microsoft.servicefabric.actors.ReminderNotFoundException" data-throw-if-not-resolved="false">ReminderNotFoundException</xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.</p>

    <p></p>
  syntax: public ReminderNotFoundException(String message, Throwable cause)
  uid: microsoft.servicefabric.actors.ReminderNotFoundException.ReminderNotFoundException(String,Throwable)
- fullName: microsoft.servicefabric.actors.ReminderNotFoundException.ReminderNotFoundException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)
  name: ReminderNotFoundException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)
  nameWithType: ReminderNotFoundException.ReminderNotFoundException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)
  parameters:
  - description: <p>The error message that explains the reason for the exception. </p>
    name: message
    type: <xref href="String?alt=String&text=String" data-throw-if-not-resolved="False"/>
  - description: <p>The exception that is the cause of the current exception, or a null reference if no inner exception is specified. </p>
    name: cause
    type: <xref href="Throwable?alt=Throwable&text=Throwable" data-throw-if-not-resolved="False"/>
  - description: <p>If true, enable suppression. </p>
    name: enableSuppression
    type: <xref href="boolean?alt=boolean&text=boolean" data-throw-if-not-resolved="False"/>
  - description: <p>If true, enable stack trace. </p>
    name: writableStackTrace
    type: <xref href="boolean?alt=boolean&text=boolean" data-throw-if-not-resolved="False"/>
  summary: >-
    <p>Initializes a new instance of the <xref uid="microsoft.servicefabric.actors.ReminderNotFoundException" data-throw-if-not-resolved="false">ReminderNotFoundException</xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.</p>

    <p></p>
  syntax: protected ReminderNotFoundException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)
  uid: microsoft.servicefabric.actors.ReminderNotFoundException.ReminderNotFoundException(String,Throwable,boolean,boolean)
- fullName: microsoft.servicefabric.actors.ReminderNotFoundException.ReminderNotFoundException(Throwable cause)
  name: ReminderNotFoundException(Throwable cause)
  nameWithType: ReminderNotFoundException.ReminderNotFoundException(Throwable cause)
  parameters:
  - name: cause
    type: <xref href="Throwable?alt=Throwable&text=Throwable" data-throw-if-not-resolved="False"/>
  syntax: public ReminderNotFoundException(Throwable cause)
  uid: microsoft.servicefabric.actors.ReminderNotFoundException.ReminderNotFoundException(Throwable)
uid: microsoft.servicefabric.actors.ReminderNotFoundException.ReminderNotFoundException*
fullName: microsoft.servicefabric.actors.ReminderNotFoundException.ReminderNotFoundException
name: ReminderNotFoundException
package: microsoft.servicefabric.actors
metadata: {}
