### YamlMime:JavaType
uid: "com.microsoft.azure.management.graphrbac.GraphErrorException"
fullName: "com.microsoft.azure.management.graphrbac.GraphErrorException"
name: "GraphErrorException"
nameWithType: "GraphErrorException"
summary: "Exception thrown for an invalid response with Graph<wbr>Error information."
inheritances:
- "<xref href=\"java.lang.Object?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.Throwable?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.Exception?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.RuntimeException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"com.microsoft.rest.RestException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
inheritedMembers:
- "com.microsoft.rest.RestException.body()"
- "com.microsoft.rest.RestException.response()"
- "java.lang.Object.clone()"
- "java.lang.Object.equals(java.lang.Object)"
- "java.lang.Object.finalize()"
- "java.lang.Object.getClass()"
- "java.lang.Object.hashCode()"
- "java.lang.Object.notify()"
- "java.lang.Object.notifyAll()"
- "java.lang.Object.wait()"
- "java.lang.Object.wait(long)"
- "java.lang.Object.wait(long,int)"
- "java.lang.Throwable.addSuppressed(java.lang.Throwable)"
- "java.lang.Throwable.fillInStackTrace()"
- "java.lang.Throwable.getCause()"
- "java.lang.Throwable.getLocalizedMessage()"
- "java.lang.Throwable.getMessage()"
- "java.lang.Throwable.getStackTrace()"
- "java.lang.Throwable.getSuppressed()"
- "java.lang.Throwable.initCause(java.lang.Throwable)"
- "java.lang.Throwable.printStackTrace()"
- "java.lang.Throwable.printStackTrace(java.io.PrintStream)"
- "java.lang.Throwable.printStackTrace(java.io.PrintWriter)"
- "java.lang.Throwable.setStackTrace(java.lang.StackTraceElement[])"
- "java.lang.Throwable.toString()"
syntax: "public class GraphErrorException extends RestException"
constructors:
- uid: "com.microsoft.azure.management.graphrbac.GraphErrorException.GraphErrorException(java.lang.String,retrofit2.Response<okhttp3.ResponseBody>)"
  fullName: "com.microsoft.azure.management.graphrbac.GraphErrorException.GraphErrorException(String message, Response<ResponseBody> response)"
  name: "GraphErrorException(String message, Response<ResponseBody> response)"
  nameWithType: "GraphErrorException.GraphErrorException(String message, Response<ResponseBody> response)"
  summary: "Initializes a new instance of the Graph<wbr>Error<wbr>Exception class."
  parameters:
  - description: "the exception message or the response content if a message is not available"
    name: "message"
    type: "<xref href=\"java.lang.String?alt=java.lang.String&text=String\" data-throw-if-not-resolved=\"False\" />"
  - description: "the HTTP response"
    name: "response"
    type: "<xref href=\"retrofit2.Response?alt=retrofit2.Response&text=Response\" data-throw-if-not-resolved=\"False\" />&lt;<xref href=\"okhttp3.ResponseBody?alt=okhttp3.ResponseBody&text=ResponseBody\" data-throw-if-not-resolved=\"False\" />&gt;"
  syntax: "public GraphErrorException(String message, Response<ResponseBody> response)"
  desc: "Initializes a new instance of the GraphErrorException class."
- uid: "com.microsoft.azure.management.graphrbac.GraphErrorException.GraphErrorException(java.lang.String,retrofit2.Response<okhttp3.ResponseBody>,com.microsoft.azure.management.graphrbac.GraphError)"
  fullName: "com.microsoft.azure.management.graphrbac.GraphErrorException.GraphErrorException(String message, Response<ResponseBody> response, GraphError body)"
  name: "GraphErrorException(String message, Response<ResponseBody> response, GraphError body)"
  nameWithType: "GraphErrorException.GraphErrorException(String message, Response<ResponseBody> response, GraphError body)"
  summary: "Initializes a new instance of the Graph<wbr>Error<wbr>Exception class."
  parameters:
  - description: "the exception message or the response content if a message is not available"
    name: "message"
    type: "<xref href=\"java.lang.String?alt=java.lang.String&text=String\" data-throw-if-not-resolved=\"False\" />"
  - description: "the HTTP response"
    name: "response"
    type: "<xref href=\"retrofit2.Response?alt=retrofit2.Response&text=Response\" data-throw-if-not-resolved=\"False\" />&lt;<xref href=\"okhttp3.ResponseBody?alt=okhttp3.ResponseBody&text=ResponseBody\" data-throw-if-not-resolved=\"False\" />&gt;"
  - description: "the deserialized response body"
    name: "body"
    type: "<xref href=\"com.microsoft.azure.management.graphrbac.GraphError?alt=com.microsoft.azure.management.graphrbac.GraphError&text=GraphError\" data-throw-if-not-resolved=\"False\" />"
  syntax: "public GraphErrorException(String message, Response<ResponseBody> response, GraphError body)"
  desc: "Initializes a new instance of the GraphErrorException class."
methods:
- uid: "com.microsoft.azure.management.graphrbac.GraphErrorException.body()"
  fullName: "com.microsoft.azure.management.graphrbac.GraphErrorException.body()"
  name: "body()"
  nameWithType: "GraphErrorException.body()"
  overridden: "com.microsoft.rest.RestException.body()"
  syntax: "public GraphError body()"
  returns:
    type: "<xref href=\"com.microsoft.azure.management.graphrbac.GraphError?alt=com.microsoft.azure.management.graphrbac.GraphError&text=GraphError\" data-throw-if-not-resolved=\"False\" />"
type: "class"
desc: "Exception thrown for an invalid response with GraphError information."
metadata: {}
package: "com.microsoft.azure.management.graphrbac"
artifact: com.microsoft.azure:azure-mgmt-graph-rbac:1.41.4
