### YamlMime:JavaType
uid: "com.azure.communication.phonenumbers.models.PhoneNumberErrorResponseException"
fullName: "com.azure.communication.phonenumbers.models.PhoneNumberErrorResponseException"
name: "PhoneNumberErrorResponseException"
nameWithType: "PhoneNumberErrorResponseException"
summary: "Exception thrown on phone number specific errors"
inheritances:
- "<xref href=\"java.lang.Object?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.Throwable?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.Exception?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.RuntimeException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"com.azure.core.exception.AzureException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"com.azure.core.exception.HttpResponseException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
inheritedMembers:
- "com.azure.core.exception.HttpResponseException.getResponse()"
- "com.azure.core.exception.HttpResponseException.getValue()"
- "java.lang.Object.clone()"
- "java.lang.Object.equals(java.lang.Object)"
- "java.lang.Object.finalize()"
- "java.lang.Object.getClass()"
- "java.lang.Object.hashCode()"
- "java.lang.Object.notify()"
- "java.lang.Object.notifyAll()"
- "java.lang.Object.wait()"
- "java.lang.Object.wait(long)"
- "java.lang.Object.wait(long,int)"
- "java.lang.Throwable.addSuppressed(java.lang.Throwable)"
- "java.lang.Throwable.fillInStackTrace()"
- "java.lang.Throwable.getCause()"
- "java.lang.Throwable.getLocalizedMessage()"
- "java.lang.Throwable.getMessage()"
- "java.lang.Throwable.getStackTrace()"
- "java.lang.Throwable.getSuppressed()"
- "java.lang.Throwable.initCause(java.lang.Throwable)"
- "java.lang.Throwable.printStackTrace()"
- "java.lang.Throwable.printStackTrace(java.io.PrintStream)"
- "java.lang.Throwable.printStackTrace(java.io.PrintWriter)"
- "java.lang.Throwable.setStackTrace(java.lang.StackTraceElement[])"
- "java.lang.Throwable.toString()"
syntax: "public class PhoneNumberErrorResponseException extends HttpResponseException"
constructors:
- uid: "com.azure.communication.phonenumbers.models.PhoneNumberErrorResponseException.PhoneNumberErrorResponseException(java.lang.String,com.azure.core.http.HttpResponse,com.azure.communication.phonenumbers.models.PhoneNumberError)"
  fullName: "com.azure.communication.phonenumbers.models.PhoneNumberErrorResponseException.PhoneNumberErrorResponseException(String message, HttpResponse response, PhoneNumberError value)"
  name: "PhoneNumberErrorResponseException(String message, HttpResponse response, PhoneNumberError value)"
  nameWithType: "PhoneNumberErrorResponseException.PhoneNumberErrorResponseException(String message, HttpResponse response, PhoneNumberError value)"
  summary: "Initializes a new instance of the Phone<wbr>Number<wbr>Error<wbr>Response<wbr>Exception class."
  parameters:
  - description: "the exception message or the response content if a message is not available."
    name: "message"
    type: "<xref href=\"java.lang.String?alt=java.lang.String&text=String\" data-throw-if-not-resolved=\"False\" />"
  - description: "the HTTP response."
    name: "response"
    type: "<xref href=\"com.azure.core.http.HttpResponse?alt=com.azure.core.http.HttpResponse&text=HttpResponse\" data-throw-if-not-resolved=\"False\" />"
  - description: "the deserialized response value."
    name: "value"
    type: "<xref href=\"com.azure.communication.phonenumbers.models.PhoneNumberError?alt=com.azure.communication.phonenumbers.models.PhoneNumberError&text=PhoneNumberError\" data-throw-if-not-resolved=\"False\" />"
  syntax: "public PhoneNumberErrorResponseException(String message, HttpResponse response, PhoneNumberError value)"
  desc: "Initializes a new instance of the PhoneNumberErrorResponseException class."
methods:
- uid: "com.azure.communication.phonenumbers.models.PhoneNumberErrorResponseException.getValue()"
  fullName: "com.azure.communication.phonenumbers.models.PhoneNumberErrorResponseException.getValue()"
  name: "getValue()"
  nameWithType: "PhoneNumberErrorResponseException.getValue()"
  overridden: "com.azure.core.exception.HttpResponseException.getValue()"
  syntax: "public PhoneNumberError getValue()"
  returns:
    type: "<xref href=\"com.azure.communication.phonenumbers.models.PhoneNumberError?alt=com.azure.communication.phonenumbers.models.PhoneNumberError&text=PhoneNumberError\" data-throw-if-not-resolved=\"False\" />"
type: "class"
desc: "Exception thrown on phone number specific errors"
metadata: {}
package: "com.azure.communication.phonenumbers.models"
artifact: com.azure:azure-communication-phonenumbers:1.0.14
