### YamlMime:JavaType
uid: "com.azure.resourcemanager.network.models.Error"
fullName: "com.azure.resourcemanager.network.models.Error"
name: "Error"
nameWithType: "Error"
summary: "Common error representation."
inheritances:
- "<xref href=\"java.lang.Object\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"com.azure.core.management.exception.ManagementError\" data-throw-if-not-resolved=\"False\" />"
inheritedMembers:
- "com.azure.core.management.exception.ManagementError.getAdditionalInfo()"
- "com.azure.core.management.exception.ManagementError.getCode()"
- "com.azure.core.management.exception.ManagementError.getDetails()"
- "com.azure.core.management.exception.ManagementError.getMessage()"
- "com.azure.core.management.exception.ManagementError.getTarget()"
- "com.azure.core.management.exception.ManagementError.toString()"
- "java.lang.Object.clone()"
- "java.lang.Object.equals(java.lang.Object)"
- "java.lang.Object.finalize()"
- "java.lang.Object.getClass()"
- "java.lang.Object.hashCode()"
- "java.lang.Object.notify()"
- "java.lang.Object.notifyAll()"
- "java.lang.Object.wait()"
- "java.lang.Object.wait(long)"
- "java.lang.Object.wait(long,int)"
syntax: "public final class Error extends ManagementError"
constructors:
- "com.azure.resourcemanager.network.models.Error.Error()"
methods:
- "com.azure.resourcemanager.network.models.Error.getInnerError()"
- "com.azure.resourcemanager.network.models.Error.validate()"
type: "class"
metadata: {}
package: "com.azure.resourcemanager.network.models"
artifact: com.azure.resourcemanager:azure-resourcemanager-network:2.1.0
