### YamlMime:JavaMember
nameWithType: DuplicateMessageException.DuplicateMessageException
type: constructor
members:
- fullName: microsoft.servicefabric.actors.DuplicateMessageException.DuplicateMessageException()
  name: DuplicateMessageException()
  nameWithType: DuplicateMessageException.DuplicateMessageException()
  summary: <p>Initializes a new instance of the <xref uid="microsoft.servicefabric.actors.DuplicateMessageException" data-throw-if-not-resolved="false">DuplicateMessageException</xref> class. </p>
  syntax: public DuplicateMessageException()
  uid: microsoft.servicefabric.actors.DuplicateMessageException.DuplicateMessageException()
- fullName: microsoft.servicefabric.actors.DuplicateMessageException.DuplicateMessageException(String message)
  name: DuplicateMessageException(String message)
  nameWithType: DuplicateMessageException.DuplicateMessageException(String message)
  parameters:
  - description: <p>input message </p>
    name: message
    type: <xref href="String?alt=String&text=String" data-throw-if-not-resolved="False"/>
  summary: >-
    <p>Initializes a new instance of the <xref uid="microsoft.servicefabric.actors.DuplicateMessageException" data-throw-if-not-resolved="false">DuplicateMessageException</xref> class with a specified error message.</p>

    <p></p>
  syntax: public DuplicateMessageException(String message)
  uid: microsoft.servicefabric.actors.DuplicateMessageException.DuplicateMessageException(String)
- fullName: microsoft.servicefabric.actors.DuplicateMessageException.DuplicateMessageException(String message, Throwable cause)
  name: DuplicateMessageException(String message, Throwable cause)
  nameWithType: DuplicateMessageException.DuplicateMessageException(String message, Throwable cause)
  parameters:
  - description: <p>The error message that explains the reason for the exception. </p>
    name: message
    type: <xref href="String?alt=String&text=String" data-throw-if-not-resolved="False"/>
  - description: <p>The exception that is the cause of the current exception, or a null reference if no inner exception is specified. </p>
    name: cause
    type: <xref href="Throwable?alt=Throwable&text=Throwable" data-throw-if-not-resolved="False"/>
  summary: >-
    <p>Initializes a new instance of the <xref uid="microsoft.servicefabric.actors.DuplicateMessageException" data-throw-if-not-resolved="false">DuplicateMessageException</xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.</p>

    <p></p>
  syntax: public DuplicateMessageException(String message, Throwable cause)
  uid: microsoft.servicefabric.actors.DuplicateMessageException.DuplicateMessageException(String,Throwable)
- fullName: microsoft.servicefabric.actors.DuplicateMessageException.DuplicateMessageException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)
  name: DuplicateMessageException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)
  nameWithType: DuplicateMessageException.DuplicateMessageException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)
  parameters:
  - description: <p>The error message that explains the reason for the exception. </p>
    name: message
    type: <xref href="String?alt=String&text=String" data-throw-if-not-resolved="False"/>
  - description: <p>The exception that is the cause of the current exception, or a null reference if no inner exception is specified. </p>
    name: cause
    type: <xref href="Throwable?alt=Throwable&text=Throwable" data-throw-if-not-resolved="False"/>
  - description: <p>If true, enable suppression. </p>
    name: enableSuppression
    type: <xref href="boolean?alt=boolean&text=boolean" data-throw-if-not-resolved="False"/>
  - description: <p>If true, enable stack trace. </p>
    name: writableStackTrace
    type: <xref href="boolean?alt=boolean&text=boolean" data-throw-if-not-resolved="False"/>
  summary: >-
    <p>Initializes a new instance of the <xref uid="microsoft.servicefabric.actors.DuplicateMessageException" data-throw-if-not-resolved="false">DuplicateMessageException</xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.</p>

    <p></p>
  syntax: protected DuplicateMessageException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)
  uid: microsoft.servicefabric.actors.DuplicateMessageException.DuplicateMessageException(String,Throwable,boolean,boolean)
- fullName: microsoft.servicefabric.actors.DuplicateMessageException.DuplicateMessageException(Throwable cause)
  name: DuplicateMessageException(Throwable cause)
  nameWithType: DuplicateMessageException.DuplicateMessageException(Throwable cause)
  parameters:
  - name: cause
    type: <xref href="Throwable?alt=Throwable&text=Throwable" data-throw-if-not-resolved="False"/>
  syntax: public DuplicateMessageException(Throwable cause)
  uid: microsoft.servicefabric.actors.DuplicateMessageException.DuplicateMessageException(Throwable)
uid: microsoft.servicefabric.actors.DuplicateMessageException.DuplicateMessageException*
fullName: microsoft.servicefabric.actors.DuplicateMessageException.DuplicateMessageException
name: DuplicateMessageException
package: microsoft.servicefabric.actors
metadata: {}
