### YamlMime:JavaMember
nameWithType: FabricCannotConnectException.FabricCannotConnectException
type: constructor
members:
- fullName: system.fabric.exception.FabricCannotConnectException.FabricCannotConnectException()
  name: FabricCannotConnectException()
  nameWithType: FabricCannotConnectException.FabricCannotConnectException()
  syntax: public FabricCannotConnectException()
  uid: system.fabric.exception.FabricCannotConnectException.FabricCannotConnectException()
- fullName: system.fabric.exception.FabricCannotConnectException.FabricCannotConnectException(String message)
  name: FabricCannotConnectException(String message)
  nameWithType: FabricCannotConnectException.FabricCannotConnectException(String message)
  parameters:
  - description: <p>The error message that explains the reason for the exception. </p>
    name: message
    type: <xref href="String?alt=String&text=String" data-throw-if-not-resolved="False"/>
  summary: >-
    <p>Initializes a new instance of the <xref uid="system.fabric.exception.FabricCannotConnectException" data-throw-if-not-resolved="false">FabricCannotConnectException</xref> class with a specified error message.</p>

    <p></p>
  syntax: public FabricCannotConnectException(String message)
  uid: system.fabric.exception.FabricCannotConnectException.FabricCannotConnectException(String)
- fullName: system.fabric.exception.FabricCannotConnectException.FabricCannotConnectException(String message, Throwable cause)
  name: FabricCannotConnectException(String message, Throwable cause)
  nameWithType: FabricCannotConnectException.FabricCannotConnectException(String message, Throwable cause)
  parameters:
  - description: <p>The error message that explains the reason for the exception. </p>
    name: message
    type: <xref href="String?alt=String&text=String" data-throw-if-not-resolved="False"/>
  - description: <p>The exception that is the cause of the current exception, or a null reference if no inner exception is specified. </p>
    name: cause
    type: <xref href="Throwable?alt=Throwable&text=Throwable" data-throw-if-not-resolved="False"/>
  summary: >-
    <p>Initializes a new instance of the <xref uid="system.fabric.exception.FabricCannotConnectException" data-throw-if-not-resolved="false">FabricCannotConnectException</xref> class with a specified error message and error code.</p>

    <p></p>
  syntax: public FabricCannotConnectException(String message, Throwable cause)
  uid: system.fabric.exception.FabricCannotConnectException.FabricCannotConnectException(String,Throwable)
- fullName: system.fabric.exception.FabricCannotConnectException.FabricCannotConnectException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)
  name: FabricCannotConnectException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)
  nameWithType: FabricCannotConnectException.FabricCannotConnectException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)
  parameters:
  - name: message
    type: <xref href="String?alt=String&text=String" data-throw-if-not-resolved="False"/>
  - name: cause
    type: <xref href="Throwable?alt=Throwable&text=Throwable" data-throw-if-not-resolved="False"/>
  - name: enableSuppression
    type: <xref href="boolean?alt=boolean&text=boolean" data-throw-if-not-resolved="False"/>
  - name: writableStackTrace
    type: <xref href="boolean?alt=boolean&text=boolean" data-throw-if-not-resolved="False"/>
  syntax: protected FabricCannotConnectException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)
  uid: system.fabric.exception.FabricCannotConnectException.FabricCannotConnectException(String,Throwable,boolean,boolean)
- fullName: system.fabric.exception.FabricCannotConnectException.FabricCannotConnectException(String message, Throwable cause, FabricErrorCode errorCode)
  name: FabricCannotConnectException(String message, Throwable cause, FabricErrorCode errorCode)
  nameWithType: FabricCannotConnectException.FabricCannotConnectException(String message, Throwable cause, FabricErrorCode errorCode)
  parameters:
  - description: <p>The error message that explains the reason for the exception. </p>
    name: message
    type: <xref href="String?alt=String&text=String" data-throw-if-not-resolved="False"/>
  - description: <p>The exception that is the cause of the current exception, or a null reference if no inner exception is specified. </p>
    name: cause
    type: <xref href="Throwable?alt=Throwable&text=Throwable" data-throw-if-not-resolved="False"/>
  - description: <p>ErrorCode of the exception </p>
    name: errorCode
    type: <xref href="system.fabric.FabricErrorCode?alt=system.fabric.FabricErrorCode&text=FabricErrorCode" data-throw-if-not-resolved="False"/>
  summary: >-
    <p>Initializes a new instance of the <xref uid="system.fabric.exception.FabricCannotConnectException" data-throw-if-not-resolved="false">FabricCannotConnectException</xref> class with a specified error message and error code.</p>

    <p></p>
  syntax: public FabricCannotConnectException(String message, Throwable cause, FabricErrorCode errorCode)
  uid: system.fabric.exception.FabricCannotConnectException.FabricCannotConnectException(String,Throwable,FabricErrorCode)
- fullName: system.fabric.exception.FabricCannotConnectException.FabricCannotConnectException(Throwable cause)
  name: FabricCannotConnectException(Throwable cause)
  nameWithType: FabricCannotConnectException.FabricCannotConnectException(Throwable cause)
  parameters:
  - name: cause
    type: <xref href="Throwable?alt=Throwable&text=Throwable" data-throw-if-not-resolved="False"/>
  syntax: public FabricCannotConnectException(Throwable cause)
  uid: system.fabric.exception.FabricCannotConnectException.FabricCannotConnectException(Throwable)
uid: system.fabric.exception.FabricCannotConnectException.FabricCannotConnectException*
fullName: system.fabric.exception.FabricCannotConnectException.FabricCannotConnectException
name: FabricCannotConnectException
package: system.fabric.exception
metadata: {}
